# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Another Attempt at a Blog
email: barcus.j[at]gmail[dot]com
description: > # this means to ignore newlines until "baseurl:"
  This is just a blog written by me, Jon Barcus.  Thoughts on code, mostly, though likely 
  many other musings.  We'll see!
baseurl: # the subpath of your site, e.g. /blog
url: "https://jonBarcus.github.io" # the base hostname & protocol for your site
twitter_username: claude_luster
github_username:  jonBarcus

# Build settings
markdown: kramdown
theme: minima
